n = (input('Digite alguma coisa: '))
print('O tipo primitivo desse valor é ', type(n))
print('É somente espaço?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanúmerico?', n.isalnum())
print('Éstá em maiúsculo?', n.isupper())
print('Ésta em minúsculo?', n.islower())
print('Éstá capitalizado?', n.istitle())
